# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UCSD CSS 1
author: Version 1, Ed Vul for SS2 2021, Version 2, John Serences for Winter 2022
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

parse:
  myst_substitutions:
    key: value
    url_website: "[Class Website](https://ucsd-css-001.github.io)"
    url_lecture: "[Lecture zoom](https://ucsd.zoom.us/j/96328022911)"
    url_lm10: "[Mon 10-12 Lab zoom (Sourabh Raja-murali)](https://ucsd.zoom.us/j/97556854018)"
    url_lm12: "[Mon 12-2 Lab zoom (Panayu Keelawat)](https://zoom.us/j/94270923304?pwd=TXVzSXBXbjE1b2RMWjdqZUtDcTZ5Zz09)"
    url_lt9: "[Tues 9-11 Lab zoom (Pulkit Agrawal)](https://ucsd.zoom.us/j/91919528909)"
    url_lf9: "[Fri 9-11 Lab zoom (Purva Kothari)](https://ucsd.zoom.us/j/99945320652)"
    url_canvas: "[Canvas (UCSD)](https://canvas.ucsd.edu/courses/32741)"
    url_slack: "[Slack](https://join.slack.com/t/css1coursechannel/shared_invite/zt-106sne18g-C_z6DvtKN2pvd2EN9M6mHg)"
    url_datahub: "[Datahub (UCSD)](https://datahub.ucsd.edu)"

# Information about where the book exists on the web
repository:
  url: https://github.com/UCSD-CSS-001/ucsd-css-001.github.io  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
